# Site settings
title: Liz Schilb
email: eschilb@gmail.com
description: > # Portfolio Website for Liz Schilb - UI Designer
baseurl: "/Liz_Schilb_Portfolio" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: eschh
github_username:  eschilb

# Build settings
markdown: kramdown
