# Site settings
title: LIZ SCHILB
email: hello@lizschilb.com
description: > # Portfolio Website for Liz Schilb - UI Designer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lizschilb.com" # the base hostname & protocol for your site
twitter_username: eschh
github_username:  eschilb
navigation:
  # - title: PORTFOLIO
  #   url: /
  # - title: ABOUT
  #   url: /about/
  # - title: BLOG
  #   url: /blog/

# Build settings
markdown: kramdown
